ruby/bigdecimal

- test/test_bigdecimal.rb
Add test cases to ensure comparing `NaN` with `NaN` never
returns `true`.
> Add test cases for `test_cmp_nan`

- test/test_bigdecimal.rb
Add test cases to ensure which sign will be returned
when BigDecimal is divided by infinity.
> Add test cases for `test_div`

- ext/bigdecimal/bigdecimal.c
- test/test_bigdecimal.rb
To ensure `ArgumentError` is raised if an invalid value is
passed to `BigDecimal#round`.
> Add test cases for `BigDecimal#round`

- ext/bigdecimal/bigdecimal.c
- test/test_bigdecimal.rb
`BigDecimal.new("-Infinity").sqrt` raises an error because this is negative value, not NaN.
> Make error messages of `#sqrt` clear

- ext/bigdecimal/bigdecimal.c
I tried to brushing up documentation (referring ruby/ruby documentation style).
How do you think about this?
> Brushing up documentation of `BigDecimal#abs`

- lib/bigdecimal/math.rb
- lib/bigdecimal/util.rb
It seems that this behavior will change in Ruby 2.4.0+.
I used version of Ruby is `ruby 2.4.0dev (2016-12-18 trunk 57108) [x86_64-darwin13]`.
Thanks.
> Brushing up documentation of math.rb and util.rb

- ext/bigdecimal/bigdecimal.c
- test/test_bigdecimal.rb
By r57130 `Float#round` is changed to accept `{ half: nil }`.
This commit follows the change.
`{ half: nil }` means the default behavior, and the default behavior
of `BigDecimal#round` is to use `BigDecimal::ROUND_MODE`.
> Change `#round` to accept `{ half: nil }` to follow r57130

- ext/bigdecimal/extconf.rb
After 53ca1882782bc05a5352020cf06e96ee19b5816a,
`have_macro` have been not used (`Kernel#have_macro` only checks
macro is defined or not).
> Remove not used `#have_macro`

- .travis.yml
Tests for Ruby 1.9.3 have been failed.
There are some reasons why tests on 1.9.3 do not work.
* Invalid syntaxes about keyword args (e.g. `**opt` or `method(a: :b)`)
* A missed macoro (`NUM2USHORT `)
Changing codes to run tests on 1.9.3 is too complex.
So drop 1.9.3 from CI.
close https://github.com/ruby/bigdecimal/issues/52
> Drop ruby 1_9_3 from CI matrix

- lib/bigdecimal/util.rb
- test/test_bigdecimal_util.rb
This commit fixes issue with String#to_d method which was inconsistent
with other to_d methods (String one returned error, while other simply
returns 0).
Also, there tests added for this case.
Associated GH issue: https://github.com/ruby/bigdecimal/issues/51
> fixes issue: #13062 - String#to_d is not raising error

- lib/bigdecimal/util.rb
Fix errors in the documentation of util.rb:
* bigdecimal/util extends the native classes with #to_d, not BigDecimal
* BigDecimal is extended with #to_d and #to_digits, not Numeric
_I already opened an issue on bugs.ruby-lang.org, [#13195](https://bugs.ruby-lang.org/issues/13195), but I guess the correct place is here?_
> Fix documentation errors for 'bigdecimal/util'

- lib/bigdecimal/util.rb
- test/test_bigdecimal_util.rb
1. Rational#to_d behaves slightly differently from BigDecimal(rational_num).
Current behavior for zero precision:
``` ruby
BigDecimal(0.3, 0)       # => 0.299999999999999988897769753748434596e0
0.3.to_d(0)              # => 0.299999999999999988897769753748434596e0
BigDecimal(22/7r, 0)     # => 0.3142857142857142857e1
22/7r.to_d(0) rescue $!  # => #<ArgumentError: negative precision>
```
Since zero precision is accepted for floats, it seems it should also be accepted for rationals.
2. All other `#to_d` methods defined in util.rb are simple wrappers around BigDecimal(), but in the case of rationals, the conversion is done by `#to_d` itself, using BigDecimal#div. IMO the conversion should be delegated to BigDecimal() instead, which also does argument checking.
The patch changes Rational#to_d …
> Let Rational#to_d use BigDecimal() and accept zero precision

- ext/bigdecimal/bigdecimal.c
- lib/bigdecimal/util.rb
bigdecimal/util "leaks" some documentation into the class documentation for the extended core classes, e.g.:
```
$ ri Integer
Integer < Numeric
(from ruby site)
------------------------------------------------------------------------------
BigDecimal extends the native Integer class to provide the #to_d method.
When you require the BigDecimal library [...]
[...other stuff that doesn't belong here...]
Holds Integer values.  You cannot add a singleton method to an Integer. Any
attempt to add a singleton method to an Integer object will raise a TypeError.
```
See also https://docs.ruby-lang.org/en/2.4.0/Integer.html, and the rdoc/ri for String, Float, Rational, BigDecimal (section "License").
This PR removes those comments from the extended core classes and instead adds a new section on …
> Document bigdecimal/util in the rdoc for BigDecimal

- ext/bigdecimal/bigdecimal.c
The documentation for BigDecimal#div currently doesn't show up at the right place:
```
$ ri BigDecimal.div
BigDecimal.div
(from ruby site)
------------------------------------------------------------------------------
div(p1, p2 = v2)
```
Instead it appears under BigDecimal#quo or the / operator.
The PR moves the existing docs to #div, and refers to it from #/ and #quo.
It also fixes some errors, clarifies the behavior and adds some examples.
> Correct and extend docs for BigDecimal#div

- ext/bigdecimal/bigdecimal.h
- ext/bigdecimal/extconf.rb
Get rid of including ruby/backward.h which is not used in
BigDecimal.
And the rule directly appended to Makefile does not work with
nmake, because the suffix .o is not replaced with .obj.
> Define RUBY_NO_OLD_COMPATIBILITY

- ext/bigdecimal/bigdecimal.c
Current behavior:
``` ruby
BigDecimal(-0.2, 0)              # => -0.200000000000000011102230246251565404e0
BigDecimal(-0.2, -1)  rescue $!  # => #<ArgumentError: argument must be positive>
d = (22/7r).to_d(9)
d.div(2, 3)              # => 0.157e1
d.div(2, 0)              # => 0.157142857e1
d.div(2, -1)  rescue $!  # => #<ArgumentError: argument must be positive>
```
The error message could be more descriptive (which argument?), furthermore, the message is wrong, since precisions can also be 0. So, something like e.g. "negative precision" would be better. Problem: the exception is raised by `GetPositiveInt()`, which is also used by BigDecimal#to_s:
``` ruby
d.to_s(3)                # => "0.314 285 714e1"
d.to_s(0)                # => "0.314285714e1"
d.to_s(-1)  rescue $!    # => …
```
> Fix error message for precision argument

- test/test_bigdecimal.rb
Resolve https://github.com/ruby/bigdecimal/pull/71#issuecomment-300696948
I added an ugly condition for Ruby 2.5.
> Add condition for mathn test. mathn was removed from Ruby 2.5

- Rakefile
- bigdecimal.gemspec
- lib/bigdecimal.rb
Hi, I added `build:mingw` task for mingw platforms. It makes that we can provide precompiled gem for mingw platform. It helps to use the latest version of bigdecimal for Windows users without devkit.
@mrkn How do you think about this?
> Added cross compilation task using rake-compiler-dock

- bigdecimal.gemspec
rake-compiler v1.0 was released on June 20, 2016.
This commit will allow developers to use rake-compiler v1.0.
> Relax a version constraint on rake-compiler

- ext/bigdecimal/bigdecimal.c
- test/test_bigdecimal.rb
For removing clone and dup instance methods in the future [#84],
we first deprecate them during Ruby 2.5 period.
> Deprecate BigDecimal#clone and #dup

- ext/bigdecimal/bigdecimal.c
- lib/bigdecimal/math.rb
- lib/bigdecimal/util.rb
- sample/linear.rb
- sample/nlsolve.rb
- test/test_bigdecimal.rb
- test/test_bigdecimal_util.rb
To remove `BigDecimal.new` from Ruby 2.6, this should be deprecated during Ruby 2.5 period.
> Deprecate BigDecimal.new

- ext/bigdecimal/bigdecimal.c
Ref: https://github.com/ruby/bigdecimal/commit/533737338db915b00dc7168c3602e4b462b23503
The warning says "BigDecimal.new is deprecated", but the message does not have the correct constructor method name. So I think users confuse when users see the message.
This change adds the correct method name, that is `Kernel.BigDecimal`.
Like https://github.com/ruby/bigdecimal/blob/a11b449ef6acb43c6b8e93fc57c1228d5163a6eb/ext/bigdecimal/bigdecimal.c#L152
What do you think?
> Tweak warning message of `BigDecimal.new`. Make the message to contain the correct constructor method name

- ext/bigdecimal/bigdecimal.c
- test/test_bigdecimal.rb
The commits in #85 was wrong.
This is correct treatment of BigDecimal#dup and #clone.
> Stop warning in dup and clone, and just return self

- ext/bigdecimal/extconf.rb
Hi, team! 👋 
I simple was exploring the source code and came across this one, it seems like unused.
the code was introduced here: https://github.com/ruby/bigdecimal/commit/02b605375c273dfae8c029588c3588b6ab85cab2#diff-92ed9076bbff06f570247479dabdeaaaR4
and then unused since: https://github.com/ruby/bigdecimal/commit/84da504a972c0c5f4692e1b39b93e98fdbfc9a1b#diff-92ed9076bbff06f570247479dabdeaaa
> Remove unused `__have_macro__` alias from extconf

- ext/bigdecimal/bigdecimal.c
Division by zero is an undefined behaviour, even when the denominator is double.  OTOH we have direct ways to generate these exceptional values.  Why not just return what you need?
> avoid division by zero

- ext/bigdecimal/bigdecimal.c
The documentation for BigDecimal#inspect refers to the previous behaviour. I've updated the documentation to the current behaviour.
> update BigDecimal#inspect documentation

- CHANGES.md
- lib/bigdecimal.rb
- test/bigdecimal/test_bigdecimal.rb
This restoration is just only for version 1.4.
> Restore `BigDecimal.new` for very old version of Rails

- CHANGES.md
- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal_util.rb
This fixes https://bugs.ruby-lang.org/issues/15426
> Fix VpAlloc so that '1.2.3'.to_d is 1.2

- lib/bigdecimal/jacobian.rb
Since https://github.com/ruby/bigdecimal/commit/3d1bdee3766b7eb611a2d845012f0eedaa3a790c, `require` is placed the way that makes class docs invisible for RDoc. See: http://ruby-doc.org/stdlib-2.6/libdoc/bigdecimal/rdoc/Jacobian.html vs https://ruby-doc.org/stdlib-2.5.0/libdoc/bigdecimal/rdoc/Jacobian.html
This PR fixes the problem.
> Fix docs for Jacobian

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal_util.rb
In `String#to_d`, it should be more forgiving for missing fractional or exponential parts, just like `String#to_f`. This adds specs and updates the behavior so that this is the case.
```ruby
$ irb
irb(main):001:0> require 'bigdecimal/util'
=> true
irb(main):002:0> '1.'.to_f
=> 1.0
irb(main):003:0> '1e'.to_f
=> 1.0
irb(main):004:0> '1.'.to_d
=> 0.0
irb(main):005:0> '1e'.to_d
=> 0.0
```
See #131 and #63 (in particular, https://github.com/ruby/bigdecimal/issues/63#issuecomment-297544464 mentions this issue). The fix in #87 did not fix this case.
> String#to_d should match String#to_f behavior with trailing decimal or 'e'

- ext/bigdecimal/bigdecimal.c
When calling `BigDecimal#round` without any argument, it casts the result to an `Integer`, while calling it with an argument (`BigDecimal#round(n)`) keeps the result as a `BigDecimal`.
I think this is an unexpected behavior, but changing it might not be backwards-compatible, so let's document it at the docs at least.
This is a port of https://github.com/ruby/ruby/pull/2149 (in case the correct place to file the PR is here instead of there).
> Update docs on `BigDecimal#round`

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
BigMath.exp would previously mutate a BigDecimal argument if the
argument was negative.  This makes a internal copy of the argument
to avoid the mutation.
Fixes Ruby Bug 8542
> Do not mutate frozen BigDecimal argument in BigMath.exp

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Both BigDecimal#clone and BigDecimal#dup return self, there is no
reason to have initialize_copy exposed as a Ruby method.
The same is true for initialize_clone and initialize_dup.
Fixes #147
> Undef BigDecimal#initialize_copy

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
This removes the taint checking.  Taint support is deprecated in
Ruby 2.7 and has no effect.  I don't think removing the taint
checks in earlier ruby versions will cause any problems.
> Remove taint checking

- .travis.yml
- appveyor.yml
- bigdecimal.gemspec
I'd like to drop Ruby 2.3 because it has been dead.
> Drop Ruby 2.3 support

- .github/workflows/benchmark.yml
- benchmark/from_integer.yml
- bigdecimal.gemspec
- ext/bigdecimal/bigdecimal.c
- ext/bigdecimal/bits.h
- ext/bigdecimal/extconf.rb
- ext/bigdecimal/feature.h
- ext/bigdecimal/static_assert.h
- test/bigdecimal/test_bigdecimal.rb
This change improves the conversion speed from small integers.
```
Comparison:
big_n9
master:   4003688.9 i/s
bigdecimal 3.0.0:   1270551.0 i/s - 3.15x  slower
big_n19
master:   5410096.4 i/s
bigdecimal 3.0.0:   1000250.3 i/s - 5.41x  slower
```
> Implement special conversions for 64-bit integers

- ext/bigdecimal/bigdecimal.c
- lib/bigdecimal/util.rb
- test/bigdecimal/test_bigdecimal.rb
- test/bigdecimal/test_bigdecimal_util.rb
Using dtoa of mode=0, we can determine the number of digits in decimal that is
necessary to represent the given Float number without errors.
This change permits digits=0 in BigDecimal(flt) and Float#to_d, and these
methods use dtoa of mode=0 when the given digits is 0.
Internal implicit conversion from Float also uses digits=0.
[Fix GH-70]
> Allow digits=0 in BigDecimal(flt) and Float#to_d

- .github/workflows/ci.yml
This helps the output of the "name" of the CI Job in the PR checks list not to say "3" when it meant "3.0".
This is a very small change, but which avoids a Float-to-String loss of characters.
An example (not from this project) of what it can look like before this change, in this picture:
Read more details, if you like: https://github.com/actions/runner/issues/849
> CI: Quote 3.0 to avoid YAML Float-to-String issue

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fix: https://github.com/ruby/bigdecimal/issues/199
Introduced in 4792a917d806ca1059c952f489413073ea51bf01
`rb_absint_size` return the number of bytes needed to fit the absolute integer, but negative integers need the sign, so one more bit, and potentially one more byte.
I would have expected the same bug to happen between `LONG_MIN` and `-ULONG_MAX` but somehow I couldn't reproduce it.
> Fix negative Bignum conversion

- ext/bigdecimal/bigdecimal.c
Treats:
- ::double_fig
- #precision
- #precs
- #_dump
- ::mode
> Enhanced RDoc for bigdecimal.c

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/helper.rb
- test/bigdecimal/test_bigdecimal.rb
- test/bigdecimal/test_bigdecimal_util.rb
> Fix trailing zeros handling in rb_uint64_convert_to_BigDecimal

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
> Fix BigDecimal#precision for single DECDIG case

- ext/bigdecimal/bigdecimal.c
Treated:
- #+@
- #add
- #+
A couple of things I've made consistent with usage over at ruby/ruby:
- The second argument to `add`, I've called `ndigits`.
- I've placed the RDoc for the methods immediately before the code, so that `Document-method` is not needed.
I also discovered that `+` and `add` are different, and have documented them separately.
> Enhanced RDoc for selected methods

- bigdecimal.gemspec
- ext/bigdecimal/extconf.rb
e.g.
```
gem "bigdecimal", github: "ruby/bigdecimal"
```
It would fail because bundler regenerates the `gemspec`, so `bigdecimal_version` is gone.
@mrkn
> Improve extconf to allow using bigdecimal as a git gem

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
> Let BigDecimal#quo accept precision

- ext/bigdecimal/bigdecimal.c
Treated:
- #+
- #-
- #<
- #<=
- #>
- #>=
- #+@
- #-@
- #add
- #mult
- #abs
- #**
- #BigDecimal
Plus some minor tweaks to previous updates.
> Enhanced RDoc for BigDecimal

- README.md
When [this table was first written](https://github.com/ruby/bigdecimal/commit/8b76f25a86abef6d21284aba2db6c2ad4759f90c) (2019-01-10), Ruby 2.7 wasn't released yet (2019-12-25).
I was just looking at it to reference which versions work, and I was worried Ruby 2.7 might not work, but it seems to work the same as 2.6. (I confirmed there's a subclass warning still too, though of course there is).
> Include Ruby 2.7 in versions table

- ext/bigdecimal/bigdecimal.c
Fixes https://github.com/ruby/bigdecimal/issues/78 by describing behaviour for positive and negative zero in the docs.
> Improve documentation of BigDecimal#sign

- ext/bigdecimal/bigdecimal.c
- lib/bigdecimal/util.rb
1. The documentation of `Float#to_d` still mentions the old default value of `precision` (`Float::DIG`). I've updated it and described what does the `precision=0` mean.
2. The description of `ndigits=0` disappeared from the documentation of `BigDecimal` function. I've added a short mention there too.
> Document precision=0 and ndigits=0 for converting from Float

- ext/bigdecimal/missing.h
`HAVE_` macros by autoconf are defined as 1.
> Suppress macro redefinition warnings

- ext/bigdecimal/bigdecimal.c
BigDecimal has no references, so it is WB protected.
> Make BigDecimal WB protected

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
`ruby/actions/.github/workflows/ruby_versions.yml@master` introduced flexible versions auntomatically. We can leave from "add X.Y version" every year.
> Use reusing workflow for Ruby versions

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fixes https://github.com/ruby/bigdecimal/issues/187 by adding a guard to `BigDecimal_divremain`. This returns early if the divider is infinity.
> Handle correctly #reminder with infinity. Fixes #187

- Gemfile
- Rakefile
- bigdecimal.gemspec
- lib/bigdecimal.rb
JRuby currently ships its own internal bigdecimal extension as part of the core libraries. In order for users to be able to add bigdecimal to their Gemfile or gem dependencies, we need to stub out the C extension and just load the extension shipped with JRuby.
In the future we will try to move our BigDecimal implementation into the gem, but for now this is the simplest way to make it installable on JRuby.
See #169
> Stub out extension build on JRuby

- bigdecimal.gemspec
```
$ gem build bigdecimal.gemspec
WARNING:  license value 'BSD-2-clause' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'BSD-2-Clause'?
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
```
> Fix the license name [ci skip]

- .github/workflows/ci.yml
- ext/bigdecimal/bigdecimal.c
* This is not supported on TruffleRuby, which requires the value to be set before RB_GC_GUARD() is called.
* See https://github.com/oracle/truffleruby/pull/2879
> Avoid RB_GC_GUARD(a) = b in bigdecimal

- ext/bigdecimal/bigdecimal.c
ruby/bigdecimal#187 has changed a behavior and ruby/spec also needed a follow up at ruby/ruby@0d8ef62fc293dc04110f36382a7e8bddec6aee15.
However, because bigdecimal is a separate gem and can be updated in older versions of ruby, `RUBY_VERSION` is not appropriate for this guard.
That means it needs bumped up `BigDecimal::VERSION`.
> Bump up to 3.1.4

- ext/bigdecimal/bigdecimal.c
This `prec` has not been used since 1f5c46dbdd1c53542ab7d37febc1a6f19b245b25.
> Remove set but unused variable

- ext/bigdecimal/bigdecimal.c
The [documents for `Kernel#BigDecimal` method](https://ruby-doc.org/3.2.1/exts/bigdecimal/Kernel.html#method-i-BigDecimal) has a typo in the second line from the bottom:
> Returns `nil` if keyword argument `exception` is `true`.
which should be:
> Returns `nil` if keyword argument `exception` is `false`.
> fix: typo in document comments of `f_BigDecimal` function

- .github/workflows/ci.yml
TruffleRuby is broken with `test_bsearch_for_bigdecimal`.
https://github.com/ruby/bigdecimal/actions/runs/5539953890/job/15003817415
> Remove TruffleRuby from CI

- ext/bigdecimal/bigdecimal.c
https://github.com/ruby/bigdecimal/pull/264#issuecomment-1626935510
Default gems need to bump up the version when a behavior change affects rubyspec tests.
> Bump up to 3.1.5

- lib/bigdecimal/util.rb
Follow up https://github.com/ruby/bigdecimal/issues/89.
`BigDecimal.new` has already been removed. This PR replaces `BigDecimal.new` with `Kernel.BigDecimal` in the documentation, following the message below:
> BigDecimal.new is deprecated; use Kernel.BigDecimal method instead.
https://github.com/ruby/bigdecimal/commit/26d84ba766e971da8eaaf2ce41e7b89935fa68da
> Update doc for bigdecimal/util

- ext/bigdecimal/bigdecimal.c
the scale of `1` is actually 0
> fixed docs for .scale

- ext/bigdecimal/bigdecimal.c
The linked methods are weakly documented at present, but stronger doc is already in a PR over at JSON.
> [DOC] Add section Methods for Working with JSON

- test/bigdecimal/test_bigdecimal.rb
There is no way to load `bigdecimal` extension in `assert_in_out_err` with `make test-bundled-gems` of ruby/ruby repository.
I added extension directory for that explicitly. I know this is ad-hoc solution. We should provide these paths to like `assert_in_out_err` assertions in `ruby/ruby` side.
> Workaround for test-bundled-gems at ruby/ruby repo

- bigdecimal.gemspec
Adding a `LICENSE` file to the bundled gem package is common practice. This way, automated OSS license compliance tools will be able to collect the full text of the license.
> Add LICENSE file to gem files

- test/bigdecimal/test_bigdecimal.rb
BigDecimal now support Ruby 2.5 or later. I removed code for old versions.
> Refine test code related unsupported Ruby version

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
macOS 11 is already EOL. I update CI matrix with `macos-arm-oss` and `macos-latest`. After that, we can test with macos-13 and Apple Silicon.
> Use macos-arm-oss and latest versions for test and benchmark CI

- test/bigdecimal/test_bigdecimal.rb
Ruby 3.4 will use a single quote instead of a backtrick as an open quote.
https://bugs.ruby-lang.org/issues/16495
> Support Ruby 3.4's new error message format

- README.md
`rake spec` is not defined in Rake tasks (`rake -T`).
`rake test` runs the tests.
This updates the documentation to help newcomers to run the test suite locally.
> Rename `rake spec` with `rake test` in documentation

- .github/workflows/ci.yml
TruffleRuby was removed on CI in #266. But the issue was fixed in the TruffleRuby 24.0 release.
> Restore TruffleRuby on CI

- bigdecimal.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/bigdecimal which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/
> Provide a 'Changelog' link on rubygems.org/gems/bigdecimal

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
Unfortunately, we lost macos-arm-oss runner from ruby org.
> Use macos-14 instead of macos-arm-oss

- lib/bigdecimal/util.rb
Noticed this very little typo while trying to understand the internals of `#to_d`
> A minor typo fix

- ext/bigdecimal/extconf.rb
If `have_header` returns `false`, `have_func` using that header also return `false` always, because that header cannot be included.
> Reduce unnecessary checks

- ext/bigdecimal/bigdecimal.c
Since #170, `big_decimal.round(0)` returns an Integer. This was surprising to me, as the documentation does not specify the behavior for this case. (It could even be seen as misleading / wrong.)
> Extend docs for round(0) [ci skip]

- ext/bigdecimal/missing.c
See ruby/ruby@8ba2c3109c0f80f285b8db2fed10d8f5f026c208
> Fix extra semicolon outside of a function in `NO_SANITIZE`

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
fix #301
For example, "0.E-9" and "0." are accepted.
FYI:
`Float()`/`.to_f` will accept "0.E-9":
https://bugs.ruby-lang.org/issues/20705
The current `Float` doesn't accept "0." but `.to_f` accepts "0.".
> Accept no digits in the fractional part

- test/bigdecimal/test_bigdecimal.rb
I've noticed test failures on truffleruby-head: https://github.com/ruby/bigdecimal/actions/runs/13139256664/job/36662137135?pr=312
```
Failure: test_s_allocate(TestBigDecimal):
Expected Exception(NoMethodError) was raised, but the message doesn't match.
Expected /undefined.+allocate.+for BigDecimal/ to match "undefined method `__allocate__' for class BigDecimal".
<nil> is not true.
/home/runner/.rubies/truffleruby-head/lib/gems/gems/test-unit-ruby-core-1.0.6/lib/core_assertions.rb:540:in `assert'
/home/runner/.rubies/truffleruby-head/lib/gems/gems/test-unit-ruby-core-1.0.6/lib/core_assertions.rb:511:in `assert_raise_with_message'
/home/runner/work/bigdecimal/bigdecimal/test/bigdecimal/test_bigdecimal.rb:300:in `test_s_allocate'
/home/runner/.rubies/truffleruby-head/lib/gems/gems/test-unit- …
```
> Fix spec NoMethodError message for .allocator on truffle Ruby

- lib/bigdecimal/math.rb
These comments are outdated
```
Note: |x|<1, x=0.9999 may not converge.
|x| must be small enough to get convergence.
```
The restriction `|x|<1` is removed with https://github.com/ruby/bigdecimal/commit/b651cb3108f23c96b8959ec3d599eb4b27712be8
`x=0.9999 may not converge` is fixed with https://github.com/ruby/bigdecimal/commit/dfc51f2f80ce8ae5dd131a01aa5a79bbcec74d8c
> Remove outdated BigMath.atan document that referrs to convergence

- test/bigdecimal/helper.rb
- test/bigdecimal/test_bigmath.rb
Precision assertion in BigMath test is missing.
BigMath uses `BigDecimal.double_fig` (16 in my env), so the calculated precision is normally >=16.
We need to test with precision several times larger than 16 to ensure that the result is really precise enough.
This assertion will be helpful when adding new methods to BigMath (example: `BigMath.tan`)
Assume `BigMath.func(v, 2 * prec)` to be the expected result which is precise enough and calculates the difference.
`assert_fixed_point_precision` is for sin and cos. `assert_relative_precision` is for other methods.
I think `BigMath.sin(x)`, `BigMath.cos(x)` with large `x` is not precise enough. This test case is not added in this pull request.
```ruby
BigMath.sin(BigDecimal('1e50'), 100) - BigMath.sin(BigDecimal('1e50'), 200)
```
> Add a precision assertion to BigMath test

- test/bigdecimal/test_ractor.rb
To keep compatibility with older Rubys, left alias value take.
See https://bugs.ruby-lang.org/issues/21262
> Use `Ractor#value` as `Ractor#take` is removed

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fixes #220, #222 and #272
BigDecimal_div and BigDecimal_div2 both have rounding problem (#272 and #328)
Integrating two division logic will make it easy to fix them.
Precision calculation for `a / b` and `a.div(b, 0)`  is improved. There is no exponential precision growth anymore.
> Integrate BigDecimal_div and BigDecimal_div2

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fixes #328
Depend on #329
Rounding needs these two:
- next digit
- boolean value `remaining digits == zero`
These are some rounding rules:
ROUND_HALF_UP: `next_digit>=5`
ROUND_HALF_DOWN: `next_digit>5 || (next_digit==5 && !remaining_zero)`
ROUND_UP: `next_digit>0 || !remaining_zero`
Currently, BigDecimal_div2 only uses next few digits.
This pull request adds extra information about remaining_digits before rounding.
> Fix division rounding

- .github/workflows/push_gem.yml
Fixed https://github.com/ruby/bigdecimal/issues/332
I will prepare the trusted publisher of rubygems.org after merging this.
> Enabled trusted publisher for rubygems.org

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Preclimit in `BigDecimal#/` and `BigDecimal#div` was accidentally dropped in #329
Some test in ruby/spec is failing. https://github.com/ruby/spec/blob/master/library/bigdecimal/limit_spec.rb
> Apply preclimit in BigDecimal_div2 when specified prec is 0

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fix #337
((Real*)x)->obj, a reference from T_DATA to VALUE, will be garbled after gc compaction. We should avoid using x->obj as possible for now. It should be removed from struct Real in the future.
> Make precision calculation in bigdecimal.div(value, 0) gc-compaction safe

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Sign of `bigdecimal**bigint` was wrong.
```ruby
(-1)**(2**50)       # => 1
(-1)**(2**50 + 1)   # => -1
(-3.0)**(2**50)     # => Infinity
(-3.0)**(2**50 + 1) # => -Infinity
(-0.5)**(2**50)     # => 0.0
(-0.5)**(2**50 + 1) # => -0.0
BigDecimal(-1)**(2**200)         # => 0.1e1
BigDecimal(-1)**(2**200 + 1)     # => 0.1e1 → -0.1e1
BigDecimal(-3)**(2**200)         # -Infinity → Infinity
BigDecimal(-3)**(2**200 + 1)     # Infinity  → -Infinity
BigDecimal('-0.5')**(2**200)     # => -0.0 → 0.0
BigDecimal('-0.5')**(2**200 + 1) # => 0.0  → -0.0
```
> Fix sign of bigdecimal**bigint

- lib/bigdecimal/math.rb
Increase `BigMath.atan(x, prec)` precision when `|x|>0.5`
`BigMath.atan(x, prec)` is calculated with `precision=prec+BigDecimal.double_fig` `when |x| <= 0.5`.
But this safe margin was not properly applied when `|x| > 0.5`.
```ruby
BigMath.atan(BigDecimal('0.2'), 100) #=> accuracy was about 116 digits
BigMath.atan(BigDecimal('0.8'), 100) #=> accuracy was about 108 digits
BigMath.atan(BigDecimal('3'), 100) #=> accuracy was about 100 digits
```
> Fix BigMath.atan precision safe margin

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Make sure that conversion from a Float works consistently with the conversion from a string representing that float.
Current `master` state:
```
pry(main)> BigDecimal(1.2)
ArgumentError: can't omit precision for a Float.
from (pry):22:in `BigDecimal'
pry(main)> BigDecimal('1.2')
=> 0.12e1
```
After this changes:
```
pry(main)> BigDecimal(1.2)
=> 0.12e1
pry(main)> BigDecimal('1.2')
=> 0.12e1
```
When precision is omitted it's set to `0`.
Fixes https://github.com/ruby/bigdecimal/issues/213
Blocked by https://github.com/ruby/bigdecimal/pull/313
> Allow BigDecimal accept Float without precision

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fix #338
`x/y == y` does not mean y converged to `sqrt(x)` if the precision of `x/y` is not high enough.
Perhaps there is a more complicated way to fix this convergence check, but #323  or #343 is better than doing it.
> Fix wrong converge check in VpSqrt

- ext/bigdecimal/bigdecimal.c
Fixes #202
(Some test already passes now, some test that still fail seems not a bug or a bug also in DECDIG=uint32_t)
```c
if (VpVtoD(&d, &e, v.real) != 1)
return rb_float_new(d);
// Range of d is: 10**-BASE_FIG <= d < 1.0
// Overflow if d*10**e > 10**DBL_MAX_10_EXP = 1e+308
if (e > (SIGNED_VALUE)(DBL_MAX_10_EXP+BASE_FIG))
goto overflow;
// Overflow if d*10**e < 10**(DBL_MAX_10_EXP - DBL_DIG) = 1e-323
if (e < (SIGNED_VALUE)(DBL_MIN_10_EXP-DBL_DIG))
goto underflow;  
```
When DECDIG is `uint32_t`, `e` is a multiple of 9. (example: -315, -324)
In this case, result of wrong calculation `(e < (SIGNED_VALUE)(DBL_MIN_10_EXP-9))` and correct calculation `(e < (SIGNED_VALUE)(DBL_MIN_10_EXP-15))` was the same just by chance.
> Fix to_f underflow check when DECDIG is uint16_t

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fix this bug
```ruby
x = BigDecimal('-0.123456789e-1000000000000000008')
x.exponent
#=> -1000000000000000008
x.to_s
```
> Fix VpNumOfChars calculation for the longest case

- .github/workflows/ci.yml
- ext/bigdecimal/bigdecimal.h
- ext/bigdecimal/extconf.rb
- test/bigdecimal/helper.rb
- test/bigdecimal/test_bigdecimal.rb
Adds CI workflow: ruby-3.4, ubuntu-latest, decdig=16bit
To compile with DECDIG=16bit:
```shell
rake clean
BIGDECIMAL_USE_DECDIG_UINT16_T=true rake compile
```
> Add DECDIG=16bit CI workflow

- ext/bigdecimal/bigdecimal.c
Fix `prec*(BASE_FIG+1)` to `(prec+1)*BASE_FIG` (if it needs one extra DECDIGs) or `BASE_FIG` (if it doesn't need extra DECDIGs)
It's just a frequently occurring mistake in bigdecimal codebase.
> Fix wrong multiplying BASE_FIG in precision calculation

- ext/bigdecimal/bigdecimal.c
- ext/bigdecimal/bigdecimal.h
- test/bigdecimal/helper.rb
Remove Unused `#define`, unused `#if 0`
Remove some hardly used `#define` macros and change it to a frequently used style.
> Remove unused #define macros

- .github/workflows/ci.yml
- ext/bigdecimal/bigdecimal.c
- ext/bigdecimal/bigdecimal.h
- ext/bigdecimal/extconf.rb
- test/bigdecimal/test_vp_operation.rb
VpDivd was using 1-index in quotient and remainder digits array. `c->frac[0]` and `r->frac[0]` was always zero.
Fix to use 0-index. Required MaxPrec of remainder reduces.
Adds a direct test for VpDivd and VpMult.
Added methods `BigDecimal#vpdivd` `BigDecimal#vpmult` are enabled only in test build.
```
Before
XXXX_YYYY_ZZZZ / 0001 = 0000_XXXX_YYYY
00XX_XXYY_YYZZ / 1000 = 0000_0000_0XXX
^^^^
unused dead digits
After
XXXX_YYYY_ZZZZ / 0001 = XXXX_YYYY_ZZZZ
00XX_XXYY_YYZZ / 1000 = 0000_0XXX_XYYY
```
`test_vpdivd_with_one` and `test_vpdivd_intermediate_zero` are tests for bug found and fixed in #374
> Fix VpDivd to fully use quotient array

- ext/bigdecimal/bigdecimal.c
Add missing RB_GC_GUARD to test-only methods: `BigDecimal#vpdivd` and `BigDecimal#vpmult`
> Add RB_GC_GUARD to test-only methods

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Improve performance of `div` and `divmod` in some case.
```ruby
BigDecimal('7'*100000).div(BigDecimal('3'*99999)) #=> 23
```
In the above example, `div` needs to calculate division with 2-digits precision. But it was internally calculating with 200000-digits precision.
This pull request also fixes the cause of this bug (found while adding test)
```
BigDecimal('3e20').div(BigDecimal('-7e-19'))
```
but this bug was fixed by a side effect of #377
> Use minimum necessary division precision in BigDecimal_DoDivmod

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_vp_operation.rb
Remove optimization path for `c->frac[i] == 1 AND first two DECDIGs of divisor and remainder is the same` condition.
I think it's worth erasing from the view of maintaining because the condition to enter this optimization path is too strict. (0.02% of the division executed in test).
Remove unused carry logic in VpDivd
It is never needed in test. Never needed in 100million random division experiment(with BASE_FIG=2 to cover many corner cases)
Carry only needs when `c->frac[i]` is wrongly calculated to `0`, but it never happens because VpDivd strictly compares `b->frac[i=0...b_prec]` with `r->frac[ind_c+i]`
> Remove dead code and ineffective optimization path form VpDivd

- ext/bigdecimal/bigdecimal.c
Removes unused `# define [MACRONAME]`
Unused `#define [MACRONAME]` are already removed in #376
PRIsVALUE is used but `# define PRIsVALUE "s"` won't work. It segfaults.
BigDecimal already doesn't support undefined PRIsVALUE environment.
> Remove unused "# define" macros

- ext/bigdecimal/bigdecimal.c
Three functions are the same except trivial code styling and rounding mode part:
```c
VpActiveRound(c.real, a.real, VP_ROUND_DOWN, iLoc); /* 0: truncate */
VpActiveRound(c.real, a.real, VP_ROUND_FLOOR, iLoc);
VpActiveRound(c.real, a.real, VP_ROUND_CEIL, iLoc);
```
> Refactor truncate floor and ceil duplicated part

- lib/bigdecimal.rb
- test/bigdecimal/test_bigdecimal.rb
Follow up of #347
and adds EXCEPTION_INFINITY EXCEPTION_NaN test
> Fix exp log power to raise "Computation results in Infinity/NaN" in EXCEPTION_INFINITY/EXCEPTION_NaN mode

- ext/bigdecimal/bigdecimal.c
Reduce usage of GUARD_OBJ and replace to RB_GC_GUARD.
BigDecimal couldn't use RB_GC_GUARD due to the structure before #344. Now we can reduce it.
GUARD_OBJ to retval is not needed
```diff
{
...
-  GUARD_OBJ(retval, foo());
+  retval = foo();
....
return CheckGetValue(retval);
}
```
Remove GUARD_OBJ of self and arg, add RB_GC_GUARD before return.
In most case, `self` is stored in stack, but some function (example: BigDecimal_to_i) calls self with non-self ruby object that needs RB_GC_GUARD.
```diff
static VALUE
BigDecimal_foobar(VALUE self, VALUE arg)
{
-  GUARD_OBJ(a, foo(self));
-  GUARD_OBJ(b, bar(arg));
+  a = foo(self);
+  b = bar(arg);
...
+  RB_GC_GUARD(a.bigdecimal)
+  RB_GC_GUARD(b.bigdecimal)
return z;
}
```
Remaining GUARD_OBJ and ENTER macro is in BigDecimal_div2 and in …
> Reduce guard obj

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Refactor this frequently appearing pattern. Many trivial variations but essentially doing the same thing.
```c
if (FLOAT) {
convertToBigDecimal(arg, prec=0);
}
else if (RATIONAL)) {
convertToBigDecimal(arg, prec=a->Prec * BASE_FIG);
}
else {
convertToBigDecimal(arg, prec=-1)
}
```
and use
```c
b = GetBDValueWithPrecMust(other, a->Prec * BASE_FIG);
// or
b = GetBDValueWithPrec(other, a->Prec * BASE_FIG);
```
Duplicated code sometimes have very small difference. This behavior will change:
```ruby
BigDecimal(7).div(0.07, 18)
```
```ruby
bigdecimal.div(float, larger_than_16)
bigdecimal.div(BigDecimal(float, 16), larger_than_16)
bigdecimal.div(BigDecimal(float, 0), larger_than_16)
bigdecimal.div(BigDecimal(float), larger_than_16)
```
```ruby
bigdecimal.div(float, 5) …
```
> Coerce to bigdecimal refactor

- lib/bigdecimal.rb
- test/bigdecimal/test_bigdecimal.rb
Follow up of #347
`BigMath.exp(rational, prec)` was converting Rational to BigDecimal with `BigDecimal(rational, 0)`
Change it to `BigDecimal(rational, prec)`.
```ruby
BigDecimal(8).power(1/3r, 40)
#=> 0.1999999999999999999999999999999986137056e1 (master)
#=> 0.2e1 (v3.2.2 and this branch)
```
Using prec to coerce is not sufficient in some case.
```ruby
BigMath.exp(30000001/3r, 1000)
```
> Coerce rational with the given prec in exp, log and power calculation

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fixes #388
Unify coerce logic in add/sub/mult/div/coerce/cmp.
There are some differences. Unify them to div's precision calculation because add/sub/mult's calculation coerce Rational with low precision.
```ruby
BigDecimal(1) / (3/7r) # Same as `BigDecimal(1) / BigDecimal(3/7r, 0)`
BigDecimal(1).div(3/7r, 50) # Same as `BigDecimal(1).div(BigDecimal(3/7r, 50), 50)`
BigDecimal(1) + (3/7r)
BigDecimal(1).add(3/7r, 50)
```
Cmp with rational will change. The original behavior was weird.
```
10/3r == BigDecimal(10/3r, prec)
1/3r == BigDecimal(1/3r, prec)
```
> Unify coerce prec calculation

- ext/bigdecimal/bigdecimal.c
BigDecimal_DoDivmod, a normal c function that returns bool result should use true/false instead of Qtrue(20)/Qfalse(0)
BigDecimal_DoDivmod is used as:
```c
if (BigDecimal_DoDivmod(self, r, &div, &mod, false)) { // This works because Qfalse is 0
return CheckGetValue(bdvalue_nonnullable(mod));
}
return DoSomeOne(self, r, '%');
```
> Use bool instead of Qtrue/Qfalse for normal c boolish value

- ext/bigdecimal/extconf.rb
- ext/bigdecimal/missing.h
Remove unused and wrong `#define false 255` definition (bug. non-zero value is truethy)
Remove unused and wrong `static int finite(double){...}` definition (compile error)
Remove unused isfinite, vabs
Remove HAVE_RB_RATIONAL_NUM check (for ruby < 2.2)
> missing.h cleanup

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Stop round/truncate in `fix` `frac` `abs` `-@` when prec limit is set
Fixes this bug
```ruby
BigDecimal.limit(1)
x=BigDecimal("#{'7'*1000}.#{'7'*1000}")
x.fix  #=> 0.7777777777777777777e1000
x.frac #=> 0.777777777777777777777777777e0
x.fix + x.frac == x #=> false
```
Stop rounding in `-@` and `abs`. Fixes inconsistency between `+@` and `-@`
```ruby
BigDecimal.limit(1)
x = BigDecimal(12345)
+x #=> 0.12345e5
-x #=> -0.1e5 → -0.12345e5
x.abs #=> 0.1e5 → 0.12345e5
```
Solves this problem
```ruby
def f(x, prec)
return f(-x, prec) if x < 0 # -@ drops precision
calculation_for_positive_case
end
def g(x, prec)
BigMath.log(x.abs, prec).mult(x, prec) # x.abs drops precision
end
```
> Fix x.fix and x.frac affected by prec limit, Stop -x and x.abs round with prec limit

- lib/bigdecimal.rb
- test/bigdecimal/test_bigdecimal.rb
```ruby
BigDecimal.limit(1)
BigMath.exp(123, 100) # This should return 100 digit precision value.
```
Wrapped with save_limit
```ruby
BigDecimal.save_limit do
BigDecimal.limit(0)
...
end
```
Compact diff: https://github.com/ruby/bigdecimal/pull/411/files?w=1
`sqrt` has the same problem. It will be fixed in #381
> Calculate exp, log, pow with the given prec even if prec limit is set

- test/bigdecimal/test_bigmath.rb
PI and E are already indirectly tested in `cos(PI(100) / 6, 100)` and in `test_exp`, but it's better to have an explicit precision test.
Related to #238
> Add BigMath::E and BigMath::PI precision test

- .github/workflows/benchmark.yml
- benchmark/from_float.yml
- benchmark/from_large_integer.yml
- benchmark/from_small_integer.yml
GitHub actions macos-latest has been updated to macos-15, and `gem install bigdecimal -v 3.0.0` began to fail.
GH-Actions failing log
```
Operating System
macOS
15.5
...
Run bundle install
bundle install
gem install bigdecimal -v 3.0.0
...
ERROR:  Error installing bigdecimal:
ERROR: Failed to build gem native extension.
...
compiling bigdecimal.c
bigdecimal.c:249:5: error: 'maybe_unused' attribute cannot be applied to types
249 |     ENTER(1);
|     ^
```
This problem seems to be fixed in https://github.com/ruby/bigdecimal/commit/6d510e47bce2ba4dbff4c48c26ee8d5cd8de1758 (released as bigdecimal-3.1.0)
Use bigdecimal 3.1.1 which is bundled in ruby-3.1.0
> Update bigdecimal version used in benchmark from 3.0.0 to 3.1.1

- ext/bigdecimal/bigdecimal.c
- lib/bigdecimal.rb
- test/bigdecimal/test_bigdecimal.rb
Introduce `BigDecimal#_decimal_shift(n)` for internal use.
`BigMath.exp` and `BigMath.log ` now uses it instead of `x * BigDecimal("1e#{shift}")`
```diff
- x = x * BigDecimal("1e#{-exponent}")
+ x = x._decimal_shift(-exponent)
```
```ruby
irb(main):002> x = BigDecimal('1'*10000)
irb(main):003> 10000.times{x*10}
=> 10000
irb(main):004> 10000.times{x._decimal_shift 1}
=> 10000
irb(main):005> 10000.times{x/10}
=> 10000
irb(main):006> 10000.times{x._decimal_shift -1}
=> 10000
```
> Implement BigDecimal#_decimal_shift for internal use

- lib/bigdecimal.rb
Stub out ruby-implemented methods (`sqrt` `exp` `log` `power`) in JRuby for now.
These methods already exist in JRuby.
It depends on new feature only implemented in bigdecimal.c: `BigDecimal(float_without_prec)` and `BigDecimal#_decimal_shift`
There are some utility functions in `lib/bigdecimal/bigdecimal.rb`: `BigDecimal::Internal.coerce_to_bigdecimal`, `BigDecimal::Internal.validate_prec`, etc.
I want to use them in BigMath in the future. At that time, I think we need to remove this `return` and fix the ruby code.
> In JRuby, don't add sqrt, exp, log, power implemented in ruby

- CHANGES.md
- ext/bigdecimal/bigdecimal.c
- Allow BigDecimal accept Float without precision
- `**`, `exp`, `log`, `power` and `sqrt` are now implemented in Ruby
- Bug fixes, refactoring, internal data structure change
- `ext/*`: 1662 deletions
- `lib/*`: 327 additions
https://github.com/ruby/bigdecimal/compare/v3.2.2...master
> Bump version to 3.2.3

- lib/bigdecimal/util.rb
- test/bigdecimal/test_bigdecimal_util.rb
Then the precision would be 0, just like with Float.
See https://github.com/ruby/bigdecimal/issues/276#issuecomment-2966635725
> Allow calling Rational#to_d without arguments

- ext/bigdecimal/bigdecimal.c
Avoid memory leak when TypedData_Wrap_Struct fail.
- First, prepare TypedData_Wrap_Struct with NULL.
- Next, allocate Real.
- Finally, bind VALUE and Real.
This was already done in f14192852fbb221099ca6f6adb3f7de8d2b5a8f3, partially broken in some commit, and accidentally dropped in #410
- BigDecimal does not run `test_no_memory_leak_BigDecimal` `test_no_memory_leak_create` test in CI.
> Fix test_no_memory_leak failure

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
Fix this bug
```ruby
(-2.0).divmod(Float::INFINITY)
#=> [-1, Infinity]
BigDecimal(-2).divmod(BigDecimal::INFINITY)
#=> [0.0, -0.2e1] 
2.0.divmod(-Float::INFINITY)
#=> [-1, -Infinity]
BigDecimal(2).divmod(-BigDecimal::INFINITY)
#=> [0.0, 0.2e1]
```
> Fix divmod and modulo by infinity to match Float#divmod and Float#modulo

- lib/bigdecimal/math.rb
`private def` has no effect in BigMath module. Change it to `private_class_method`
```ruby
module BigMath
module_function
def foo; end 
private def foo; end
private_class_method def foo; end
end
```
> Make internal BigMath method a private method

- lib/bigdecimal.rb
- test/bigdecimal/test_bigdecimal.rb
Follow up of #438
Fix precision bug when `x.power(y, prec)` gets larger than `1e+4342944819032518`.
> Fix precision of x.power(y, prec) when the result is nearly infinity
