- README.md
> Appveyor badge for windows build status

- test/test_bigdecimal.rb
Add test cases of `-0`, `Infinity` and `-Infinity`.
> Add test cases for `BigDecimal#abs`

- ext/bigdecimal/bigdecimal.c
- ext/bigdecimal/bigdecimal.h
- ext/bigdecimal/extconf.rb
- test/test_bigdecimal.rb
https://bugs.ruby-lang.org/issues/12952
> Introduce half: optional argument for BigDecimal#round

- ext/bigdecimal/bigdecimal.c
- test/test_bigdecimal.rb
https://bugs.ruby-lang.org/issues/12161
> Fixing [Feature #12161]

- lib/bigdecimal/util.rb
* clarify that the receiver is not modified
* add docs for Float#to_d with precision
* improve explanation of String#to_d
* adapt style and variable naming to core docs
* add/improve examples
* add references to BigDecimal.new
_I guess this should merge without conflicts after #58; if not I can rebase._
> Revise documentation for bigdecimal/util

- test/test_bigdecimal.rb
Add assertions for negative value case.
> Add test cases for `BigDecimal#round`

- test/test_bigdecimal.rb
Add assertions for negative value case.
> Add test cases for `BigDecimal#truncate`

- lib/bigdecimal/util.rb
- test/test_bigdecimal_util.rb
> add NilClass#to_d

- lib/bigdecimal/util.rb
- test/bigdecimal/test_bigdecimal_util.rb
This pull request consists of #62 and tests for the changes in it.
> #62 and tests

- ext/bigdecimal/bigdecimal.c
Hopefully can be merged before Ruby 2.6 release.
> Mention exception: argument

- bigdecimal.gemspec
> Add lib/bigdecimal.rb to files array

- appveyor.yml
- ext/bigdecimal/util/extconf.rb
> Fix install on mingw32

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal_util.rb
Cherry-picking these commits from #132 back to the 1.4 branch. Not sure if there was a better way to do this.
> Backport String#to_d fix to 1.4 branch

- appveyor.yml
- ext/bigdecimal/util/extconf.rb
> Backport 138

- ext/bigdecimal/util/extconf.rb
> Fix for gem install

- Rakefile
- bigdecimal.gemspec
- lib/bigdecimal.rb
Dropping "fat gem" support as discussed in #148.
> Drop support for "fat gem" release

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
> Return US-ASCII string from BigDecimal#to_s

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
> Make BigDecimal#round with argument < 1 return Integer

- ext/bigdecimal/bigdecimal.c
the library is already included by ```#include <math.h>```
> remove duplicated include

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
I'd like to revert some commits due to SEGV occurred on Windows.
> Revert commits against segv on windows

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
> Allow passing both float and precision in BigDecimal#div

- ext/bigdecimal/bigdecimal.c
This fixes #290 .
```
$ ruby -v -Ilib issue290.rb
ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]
21696
21696
21696
21696
21696
21696
21696
21696
21696
21696
```
> Fix memory leak in VpAlloc by exception

- ext/bigdecimal/bigdecimal.c
Forgot to update this part in #344
> Fix compiling issue (when BIGDECIMAL_DEBUG is 1)

- ext/bigdecimal/bigdecimal.c
- test/bigdecimal/test_bigdecimal.rb
> Fix modulo/remainder of negative zero
